name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger on push to the main branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions to allow the GITHUB_TOKEN to be used to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job is skipped for a simple static site, 
  # but is useful if you had a build step (like generating JS or CSS).
  # We use the 'deploy' job directly for CD.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4
      
      - name: 📁 Setup Pages
        uses: actions/configure-pages@v5

      - name: ⬆️ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire repository root directory
          path: './' 

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
